image: alpine:latest

before_script:
  - apk update
  - apk add gcc git clang-dev cargo

test1:
  stage: test
  script:
    - cargo test
    - cargo build
    - gcc -o minimp3 cver/minimp3_test.c -lm -Ltarget/debug -lminimp3port -ldl -lpthread
    - sh scripts/test.sh
