image: rustlang/rust:nightly-slim

style:
  stage: test
  script:
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy --all-targets

substance:
  stage: test
  script:
    - export RUSTFLAGS="-Zsanitizer=address"
    - export ASAN_OPTIONS=detect_odr_violation=0
    - cargo test
    - cargo build
    - mv target/debug/minimp3 minimp3
    - sh scripts/test.sh
