image: alpine:latest

before_script:
  - apk update
  - apk add git cargo

test1:
  stage: test
  script:
    - cargo test
    - cargo build
    - mv target/debug/minimp3 minimp3
    - sh scripts/test.sh
