image: rust

style:
  stage: test
  script:
    - rustup component add rustfmt clippy
    - cargo fmt --all -- --check
    - cargo clippy --all --all-targets

substance:
  stage: test
  script:
    - cargo test
