[package]
name = "minimp3port"
version = "0.1.0"
authors = ["Niv Kaminer <nivkner@zoho.com>"]

[dependencies]
libc = { version = "0.2", default-features = false }

[dev-dependencies]
quickcheck = "0.7"
